### ISSUE TITLE
Code Modification

### ISSUE THREAD

**Issue by I-Thibaud** [tarot231/qgis-operate-multiple-layers-plugin#1]
Hi,

Thanks for plugin. It is very useful. 

I have a conflict with an other plugin. I add this piece of code in __init__.py (line 94) in  def slot_mapToolSet
        if self.canvas.mapTool().action() is None :
            return

Plugin still works and conflict disappears.

![image](https://github.com/tarot231/qgis-operate-multiple-layers-plugin/assets/84328873/245ae378-2d4e-4d79-bc89-7ab87aebd6f7)

Do you agree to correct it ?

Thanks !

Thibaud

**Comment by tarot231** [comment]
Does v0.3.2 still conflict? That code seems to be old.

**Comment by I-Thibaud** [comment]
Thanks you, that's work with v0.3.2.

Plugin is very good !

Have a good day.
